### ISSUE TITLE
PHP Parse Error ?? T_USE

### ISSUE THREAD

**Issue by teewhey** [wa0x6e/ResqueBoard#11]
I'm seeing this in my apache logs when trying to access to ResqueBoard 

PHP Parse error:  syntax error, unexpected T_USE, expecting T_FUNCTION in /var/www/ResqueBoard/src/ResqueBoard/Lib/Service/Mongo.php

Any idea where could have gone wrong??

**Comment by wa0x6e** [comment]
What's you PHP version ? The lastest master is only compatible with php 5.4, as it's using trait. Next beta (4) will come with php5.3 compatibility

**Comment by teewhey** [comment]
I see.... My PHP version is 5.3.3-7

PHP 5.3.3-7+squeeze15 with Suhosin-Patch (cli) (built: Mar  4 2013 13:11:17)
Copyright (c) 1997-2009 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Suhosin v0.9.32.1, Copyright (c) 2007-2010, by SektionEins GmbH

**Comment by wa0x6e** [comment]
You should use the beta-2, or wait for the next beta, in one week.

**Comment by teewhey** [comment]
I have managed to get ResqueBoard up and running.
My setup is having fresque running on Server A, and ResqueBoard running on Server B.

On FresqueBoard, I see "A 500 occured while fetching the list of workers" and "A 500 occured while fetching the list of queues".
Any configurations that I might miss out?

**Comment by wa0x6e** [comment]
The lastest master should be compatible php 5.3 now.

Can you connect to the Redis and Cube server ?
You can check what's wrong by loading the page `/api/workers`, it'll display a more meaningful error message

**Comment by teewhey** [comment]
On the ResqueBoard, I've installed Cube here....
The redis resides on the other server.

Based on my setup that the ResqueBoard runs on a separate server, what are the stuffs that I have to configure?

Btw. the error that I get on the api/workers page is "Oups ! Something went wrong, Redis server went away"

**Comment by wa0x6e** [comment]
If cube is installed on the same server as ResqueBoard, it should works by default.
But you must configure ResqueBoard to connect properly to your Redis server.

Assuming your workers are running on another server, Redis must be on that other server too, unless you're on a master/slave setup with a slave on the ResqueBoard server.

Assuming you have a standard redis server (only one master), you should edit the src/ResqueBoard/Config/Core.php file, line 50-51, with your own redis server address. Should be the IP of the other machine.

**Comment by teewhey** [comment]
Aha ... so that is where I missed out.....
Able to get it running now. Thank you so much.

**Comment by wa0x6e** [comment]
You're welcome
