### ISSUE TITLE
php-resque-ex for Resqueboard Installation

### ISSUE THREAD

**Issue by teewhey** [wa0x6e/ResqueBoard#12]
Hi kamisama,

The ResqueBoard installation notes, the php-resque-ex should be replaced on my php codes or the Fresque directory or on the ResqueBoard server or all of them?

This is my current setup :

Server 1 : Fresque + My Codes
Server 2 : ResqueBoard

**Comment by wa0x6e** [comment]
Hi,

I don't quite understand your question, but php-resque-ex and fresque is
installed automatically when ResqueBoard is installed via Composer.

If you already have a working code with its own php-resque-ex and fresque,
then leave them as is.

Just make sure that you're using the same version of php-resque-ex and
fresque in your current code.

**Comment by teewhey** [comment]
Let me elaborate one step at the time, hopefully I can convey it correctly....
Let's start with the ResqueBoard server first....

I've installed according to the installation note, however I'm a bit confused on the php-resque-ex portion in the installation note. Where should I be replacing php-resque-ex?

**Comment by wa0x6e** [comment]
Ok,if you already have php-resque-ex installed in your code, you don't need
to replace it, just skip that step.

This step is for those who have php-resque installed in their application,
which is not compatible with Resqueboard, and should be replaced by
php-resque-ex.

**Comment by bolbol123** [comment]
Hi, 

Regarding same issue, we have updated both fresque and php-resque-ex to the same version (1.2.5) but so far we couldn't manage to see the real time stats on ResqueBoard main page. It's just the total number of jobs and overall stats of each queue and nothing realtime.  

Need to mention:
-Our ResqueBoard is hosted on a separate server.
-We can see a traffic on udp port 1180 on both servers. 

Just nothing shows up!

**Comment by wa0x6e** [comment]
There was an issue with the monolog shipped with resqueboard. Change the
dependency version to 1.6, it should fixthe bug if your issue was with your
webserver not on the utc timezone

**Comment by teewhey** [comment]
Hi kamisama, are you refering to the monolog dependency of Resqueboard or the fresque??

**Comment by wa0x6e** [comment]
Of php-resque-ex. I'll update it later, I'm on the move these days
