### ISSUE TITLE
No graphs, no cube data?

### ISSUE THREAD

**Issue by galvani** [wa0x6e/ResqueBoard#13]
hello,
i did setup everything as described, but i don't get any data from the cube, in mongo there are events present but no metrics generated, though I am not sure it is supposed to.
I don't get any graphs, initial ajax returns, i guess, valid response with 0 values.

What i do see:
workers (processed/failed)
queues

I don't see any jobs

am i doing something wrong?
thx

**Comment by wa0x6e** [comment]
in the top right corner, there's 3 little circles. What colors are they ? The rightmost circle should be blue on page load, then turn green.

If there is data in mongo, the cube collector should be running. Did you also start the cube evaluator ?

**Comment by galvani** [comment]
hello, thanks, they are all green. the data is being collected as there are events being logged from cube. there are no metrics produced though. both processes are running with no errors in log file.

**Comment by wa0x6e** [comment]
Do you see the cube dashboard on localhost:1081 ?
Are you running on the default port and on localhost ?

**Comment by wa0x6e** [comment]
Any update ?

**Comment by galvani** [comment]
Hello, sorry for the delay. and please know: i appreciate your help. it gives 404 (not http response, just the text/number). I did notice some bug/fail with nginx. i do use nginx too.

**Comment by galvani** [comment]
doh, i did close it :-( sorry

**Comment by wa0x6e** [comment]
Seems like something wrong with Cube, I'll try to find a way to confirm that.
What's the bug with nginx ?

**Comment by galvani** [comment]
hello, i did find the issue with cube. i did start cube from incorrect directory. this problem is described on cube's repo site. my fault, my bad. sorry and thanks for help
