### ISSUE TITLE
Call to undefined method ResqueBoard\View\MyView::setTemplate()

### ISSUE THREAD

**Issue by jstuhli** [wa0x6e/ResqueBoard#14]
After a first, fresh install of ResqueBoard and its dependencies via composer, the following error appears when accessing ResqueBoard/src/ResqueBoard/webroot/:

Fatal error: Call to undefined method ResqueBoard\View\MyView::setTemplate() in /var/www/html/ResqueBoard/src/ResqueBoard/View/MyView.php on line 49

It would appear that slim (2.3.1) no longer has setTemplate() method

**Comment by wa0x6e** [comment]
Fixed in the latest master
