### ISSUE TITLE
Class 'Redis' not found

### ISSUE THREAD

**Issue by jstuhli** [wa0x6e/ResqueBoard#15]
After clean install (git clone + composer install), accessing ResqueBoard/src/ResqueBoard/webroot/ gives this error:

Fatal error: Class 'Redis' not found in /var/www/ResqueBoard/src/ResqueBoard/Lib/Service/Redis.php on line 37

**Comment by wa0x6e** [comment]
Travis is telling me the same thing.

Do you have the php-redis extension installed ?

**Comment by jstuhli** [comment]
I do now, and now it works fine :)
