### ISSUE TITLE
No job details

### ISSUE THREAD

**Issue by ravindar** [wa0x6e/ResqueBoard#17]
Hi I have ResqueBoard installed and all the components like Redis/Mongo/Cube are working and connecting. I can also see jobs getting processed, but when i click on a job to get more details, I don't see any information under Processed Jobs. Also no data is coming thru logs.  I am using PHP Resque and not PHP Resque Ex, just in case that is the cause? Any help is greatly appreciated.

Thanks
Ravindar

**Comment by wa0x6e** [comment]
Yes, it's the cause. php-resque-ex is far behind the original fork, I'm
working on a PR that will re-merge all ex feature into the original branch.
There'll be no more fix or new features in the ex branch.

**Comment by ckmaresca** [comment]
I know this is close, any updates on when/if this merge might happen?  I'm asking as I just spent many hours setting up resque-ex to work with resqueboard and just discovered this post...

**Comment by pwhelan** [comment]
+1
