### ISSUE TITLE
without logs

### ISSUE THREAD

**Issue by JrBarbosa** [wa0x6e/ResqueBoard#30]
Hello Kamisama,

Please help me.

I have installed the resqueboard, but I can't see any log, in last activities and on the jobs overview, all the logs are blank.

This can be time zone issue, but I'm using the time zone America/Sao_Paulo in my server. 
What I can do to fix it?

![image](https://cloud.githubusercontent.com/assets/4378657/2780647/2bc917de-cb0a-11e3-9a25-83c1eb286245.png)

Tks

**Comment by wa0x6e** [comment]
Yes, it's possible it is a timezone issue if your computer and the server are not on the same timezone.
It's a known issue, and it's in my to-do list

**Comment by JrBarbosa** [comment]
The timezone was correct, it was a mistake to redirect the logs to the cube.

Tks!
