### ISSUE TITLE
Does it works with the original port?

### ISSUE THREAD

**Issue by JCMais** [wa0x6e/ResqueBoard#32]
Does this interface works with the current version of the default port?

Or there is anything that it needs that is possible only with your fork? (php-resque-ex)

**Comment by wa0x6e** [comment]
Only with the fork (for now).
But with the addition of the logger system in the latest master, it should be easily implemented on the default fork.

With all the changes in php-resque, that is the last feature to merge back before deprecating this fork.

I plan to do it someday, but help is welcome.

**Comment by JCMais** [comment]
Can you make a checklist with what needs to be modified to make it work with php-resque?

I can give some help.

**Comment by wa0x6e** [comment]
There's 2 things :
- [ ] Add a timer to some actions (to have metric like "job completed in x ms")
- [ ] Log the necessary datas

Currently, php-resque only log a string message. The newly implemented logger can also takes an array of data, and should be used to send those datas properly to the Monolog logger.

Read php-resqre-ex code source to get an idea of which datas are passed to the logger.
