### ISSUE TITLE
Job output and warnings

### ISSUE THREAD

**Issue by themao** [wa0x6e/ResqueBoard#34]
Hello Kamisama,

I have noticed that there's no job output logging. Is it possible to pass via Monolog to Mongo? And is it a desired functionality? Because in my project we need to see the output of the script.

And I also see that warnings/notices are not handled by try/catch blocks, so I've made a small workaround that replaces them with exceptions (using events). How do you think, is that a good behavior and is it worth forking and creating pull-request? Or better solution will be just to buffer the output and send it to ResqueBoard as I described above?

Thanks.

**Comment by wa0x6e** [comment]
So you want to send the log to ResqueBoard, and somewhere else at the same time ?

**Comment by themao** [comment]
No, just to ResqueBoard. The stdout & stderr of the job.

**Comment by wa0x6e** [comment]
I don't quite understand. You want to redirect all stdout and stderr to a file ? Because they're not sent to Cube ?

**Comment by themao** [comment]
Yes, the output of the script that is echoed or printed. And not to a file, but to the Cube, to see it in the Resqueboard.

**Comment by wa0x6e** [comment]
I don't quite understand what you want, can you explain more in details ?

**Comment by themao** [comment]
Well, when you click on a successfully finished job here http://resque.kamisama.me/jobs/view, you can see only args that were passed. What I want is to see the output of the job - everything that the script echo'ed during the execution.

**Comment by wa0x6e** [comment]
I see.

How are  you starting/managing your workers ?

**Comment by themao** [comment]
From bash console.

**Comment by wa0x6e** [comment]
Mhmmm ... It's a functionality that should be implemented on the php-resque side.
You can try opening a ticket over there, and propose logging the job output.

**Comment by themao** [comment]
Yes, indeed. Sorry for mixing up the repos, but I also use your fork of php-resque (php-resque-ex). I will create an issue there.

**Comment by wa0x6e** [comment]
I think you can directly ask it on php-resque repo, instead of the fork. The fork will be merged back into the original soon.
