### ISSUE TITLE
Cache issues

### ISSUE THREAD

**Issue by shadyb** [wa0x6e/ResqueBoard#38]
There appears to be issues with the resqueboard content loading on page refresh. I have to force refresh the page several times before the content loads. First time I've encountered a tool that caches so aggressively. Do you know exactly what is causing it ? I have set all the relevant expiry/no-cache headers to no avail.

**Comment by wa0x6e** [comment]
What do you mean by "before the content loads" ? Is it displaying a page with all the menus, but no components (graphs, etc ...), or just a plain blank page ?

For the former case, I think it's an issue with Angularjs, the project's stuck with a very outdated version.

**Comment by shadyb** [comment]
It is displaying the menu with no components.

Okay, so you suspect angularJS; how much work would it take to update it to a newer version ? Would it simply be a case of swapping out the .js file (as is usually the case with jquery for example) ?

**Comment by wa0x6e** [comment]
I'm not familiar with the newer version of AngularJS. The version used is among the first, so not very stable. Maybe the issue is with the loading order of the javascript too.

Do you have the same symptoms as in this ticket ? https://github.com/kamisama/ResqueBoard/pull/23

**Comment by shadyb** [comment]
Yes, applying the fix mentioned in that ticket has resolved the load issues. Strange, have you merged that  fix into the master branch ?

**Comment by wa0x6e** [comment]
You applied that change ? https://github.com/kamisama/ResqueBoard/pull/23/files

**Comment by shadyb** [comment]
I did a clone of the repo approx. 2 months ago and that patch was applied around 11 months ago. I copied and pasted the contents of the `assets/js/main.js` file into the `src/ResqueBoard/webroot/js/main.js` file and now I no longer experience the "blank component" problem. It looks like it was applied to the wrong file. I'm not sure what the assets/js/\* folder is used for but since it is not in the webroot dir I presume it is not being used by the front-end. I can do a pull request and update `src/ResqueBoard/webroot/js/main.js` if you like ?

**Comment by paco3346** [comment]
I can also vouch for @shadyb's fix working. I was having the same issue and adding that dependency in `src/ResqueBoard/webroot/js/main.js` solved the issue.

**Comment by shadyb** [comment]
Thanks @paco3346. I will do a PR sometime soon and patch it.

**Comment by shadyb** [comment]
Thanks for fixing the issue paco3346; forgot about resqueboard for awhile.
