### ISSUE TITLE
Can't see any information about the jobs

### ISSUE THREAD

**Issue by OptimusMarlboro** [wa0x6e/ResqueBoard#4]
I managed to install ResqueBoard. I am able to see the running workers, processed/failed jobs etc but I can't see anything when I click on Logs or Jobs tab, I don't get any log or job.

**Comment by OptimusMarlboro** [comment]
Got it know, in the installation document you wrote
When starting your workers, set the :

LOGHANDLER to Cube
LOGHANDLER to udp://127.0.0.1:1180 (edit if your Cube server is running on a different host and/or port)

the last line should read

LOGHANDLERTARGET ....

**Comment by wa0x6e** [comment]
Hi,

Thanks for noticing it, I'll correct it as soon as I come back from my trip.

**Comment by wa0x6e** [comment]
Fixed
