### ISSUE TITLE
Question : How do I flush all entries in the MongoDB?

### ISSUE THREAD

**Issue by teewhey** [wa0x6e/ResqueBoard#41]
Not really an issue. Just a question on is it safe to flush all entries in MongoDB using db.cube_development.remove()  ??

**Comment by wa0x6e** [comment]
What do you want to achieve ? Just remove ResqueBoard ? Yes, all data in cube are just for ResqueBoard, removing them does not affect your resque instances

**Comment by teewhey** [comment]
I just want to clear off the data... I don't need the older data anymore....
The Resqueboard will still be running

**Comment by wa0x6e** [comment]
In that case, yes, you should drop the cube_development database

**Comment by teewhey** [comment]
If I drop it, do I need to recreate it? Pardon me as I'm not so familiar with MongoDB.

**Comment by wa0x6e** [comment]
No, if needed, Cube will recreate it automatically

**Comment by teewhey** [comment]
Ah... okay ... thank you very much.
