### ISSUE TITLE
Configuration troubles

### ISSUE THREAD

**Issue by dietrich-stein** [wa0x6e/ResqueBoard#8]
First of all, thank you for creating such a beautiful dashboard for php-resque. I look forward to using it as my primary method of monitoring job queues.

However, first I need to finish setting it up--which I believe to be 90% complete. I am missing two things.

1) Getting cube running. When I run the provided commands I am not returned to the shell prompt... I am only able to ^C out. What am I doing wrong?

```
node usr/local/node_modules/cube/bin/collector.js 2>&1 >> /usr/local/var/log/cube/collector.log &
[2] 13107
[1]   Exit 8                  node bin/collector.js 2>&1 >> /usr/local/var/log/cube/collector.log
root@li550-108:/# Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.
^C
```

```
node usr/local/node_modules/cube/bin/evaluator.js 2>&1 >> /usr/local/var/log/cube/evaluator.log &
[3] 13126
root@li550-108:/# Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.
^C
```

2) Futhermore, I have no workers, jobs, or anything yet. So when I load the dashboard I receive a 500 error from "http://queue.mydomain.com/api/stats?fields=scheduled,pending" stating:

array_combine(): Both parameters should have at least 1 element

Am I correct to assume this will go away once there is data?

**Comment by wa0x6e** [comment]
1) The node command should run the node in the background. Try to not ^C, but press enter or space to "flush" the terminal.

2) Are you on the latest master ? Because the scheduled and pending fields should not exists.

**Comment by dietrich-stein** [comment]
Thanks for your prompt reply. Pressing enter was just what I needed... next I will see if I can fashion an init script so that I don't need to start cube manually upon reboot.

I do believe I'm on the lastest master though... here is the line on 5 second timeout:
https://github.com/kamisama/ResqueBoard/blob/master/src/ResqueBoard/webroot/js/app.js#L1534

**Comment by wa0x6e** [comment]
My bad, I thought you were talking about the queues API, since your subdomain was starting with queues.
Yes, that error will go away once there is data, the next build will not have that issue

**Comment by wa0x6e** [comment]
I can't reproduce the array_combine error on a clean resqueboard. 
Are you connected to Cube, Mongodb and redis correctly ?
What version of PHP are you running on ?

**Comment by wa0x6e** [comment]
"Should" be gone after the big refactoring of beta-2 and 3
